# -*- coding: utf-8 -*-
"""4_Despliegue_Modelamiento_analisis_cultivo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UMMabmVWflhW5YiAx_Qo30ZqwEmkyino

# Pipes - Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Aplicar tubería
"""

#Cargamos librerías principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import pickle
filename = 'modeloCV.pkl'
pipeline = modelTree,variables,labelencoder,min_max_scaler = pickle.load(open(filename, 'rb'))
pipeline

#Recorda documentar esto para poder ejecutar streamlit
#data = pd.read_csv("datos_futuros.csv")
#data.head()

#Interfaz gráfica
#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Predicción estado fisico cultivo')

areaSembrada = st.slider('Area Sembrada(ha)', min_value=0, max_value=1000, value=20, step=1)
areaCosechada = st.slider('AREA COSECHADA(ha)', min_value=0, max_value=350, value=20, step=1)
produccion = st.slider('PRODUCCION(t)', min_value=0, max_value=3500, value=20, step=1)
rendimiento = st.slider('RENDIMIENTO(t/ha)', min_value=0, max_value=10, value=20, step=1)
cultivo = st.selectbox('CULTIVO', ["Aguacate demAs variedades", "MaIz Tradicional", "Frijol", "'LimOn Pajarito"])
cicloCultivo = st.selectbox('CICLO CULTIVO', ["Permanente", "Transitorio"])
grupoCultivo = st.selectbox('GRUPO CULTIVO', ["Frutales", "Cereales","Leguminosas"])
subGrupo = st.selectbox('SUBGRUPO', ["Demas frutales", "Cereales","Leguminosas", "CItricos"])
nombreCientifico = st.selectbox('NOMBRE CIENTIFICO CULTIVO', ["Persea americana", "Zea mays","Phaseolus sp", "Citrus limon L."])


#Dataframe
datos = [[areaSembrada, areaCosechada,produccion,rendimiento,cultivo,cicloCultivo,grupoCultivo,subGrupo,nombreCientifico]]
data = pd.DataFrame(datos, columns=['Area Sembrada(ha)', 'AREA COSECHADA(ha)', 'PRODUCCION(t)', 'RENDIMIENTO(t/ha)', 'CULTIVO', 'CICLO CULTIVO', 'GRUPO CULTIVO','SUBGRUPO','NOMBRE CIENTIFICO CULTIVO']) #Dataframe con los mismos nombres de variables

#Se realiza la preparación debe ser igual al aprendizaje
data_preparada=data.copy()
data_preparada = pd.get_dummies(data, columns=["'CICLO DE CULTIVO'"], drop_first=True, dtype=int)
data_preparada = pd.get_dummies(data, columns=['CULTIVO', "'GRUPO CULTIVO'", 'SUBGRUPO', "'NOMBRE CIENTIFICO CULTIVO'"], drop_first=False, dtype=int)

data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

"""# **Predicciones**"""

#Hacemos la predicción con el Tree
Y_fut = modelTree.predict(data_preparada)
print(Y_fut)

print(labelencoder.inverse_transform(Y_fut))

data['Tree']=labelencoder.inverse_transform(Y_fut)
data.head()

#Hacemos la predicción con Ranfom Forest
Y_fut = model_rf.predict(data_preparada)
data['RF']=labelencoder.inverse_transform(Y_fut)
data.head()